version: '3'


dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']
tasks:
  activate-pyenv:
    cmds:
      - pyenv activate 3.9.1/envs/bedrock-development
  working-with-foundation-model:
    cmds:
      - python 01-working-with-foundation-model.py  
#      - glow build/01-output.md
  working-with-embeddings:
    cmds:
      - python 02-working-with-embeddings.py
  
  working-with-vector-database:
    cmds:
      - python 03-working-with-vector-database.py
  
  setup-port-forwarding-for-pg:
    cmds:
      - ssh -L $PG_HOST_PORT:$PG_HOST_NAME:$PG_HOST_PORT ec2-user@$BASTION_HOST_IP_ADDRESS -N
  connect-to-psql:
    cmds:
      - psql -h localhost -U postgres
  setup-port-forwarding-for-os:
    cmds:
      - echo "ssh -L 8080:$OS_HOST_NAME:$OS_HOST_PORT ec2-user@$BASTION_HOST_IP_ADDRESS -N"
      - ssh -L 8080:$OS_HOST_NAME:$OS_HOST_PORT ec2-user@$BASTION_HOST_IP_ADDRESS -N
  set-up-os-cli-profile:
    cmds:
      - opensearch-cli profile create --auth-type basic --endpoint https://localhost:9200 --name opensearch-1


  